### ISSUE TITLE
Update cht-user-management chart

### ISSUE THREAD

**Issue by paulpascal** [medic/helm-charts#19]
This ticket is related to the changes brought from [move contact feature](https://github.com/medic/cht-user-management/issues/12) which add a new image and have **three** services (web app, worker, and redis) now instead of one.

To accommodate these changes, we need to bring some update to the `cht-user-management` helm chart by:

- [ ] adding another block for `cht-user-management-worker` in [values](https://github.com/medic/helm-charts/blob/main/charts/cht-user-management/values.yaml)  
- [ ] adding that as a new [depedency](https://github.com/medic/helm-charts/blob/main/charts/cht-user-management/Chart.yaml#L11) . 

We'll want to make sure the service names of the worker are reachable to the main pushed to prod instead of just one (main).

cc: @Hareet @mrjones-plip

**Comment by paulpascal** [comment]
Hello @Hareet, is there please an update on this ?
Thanks 🙏

**Comment by PhilipNgari** [comment]
Hello @Hareet  Kindly help unblock us here. cc @medic/site-reliability-engineering

**Comment by henokgetachew** [comment]
I'm going to be handling this this week. I will reach out if I need more information

**Comment by mrjones-plip** [comment]
in case it's relevant to pushing newer versions with move contact live to any of the 4 production instances of the tool, there's a pending [PR to update how pushes are done](https://github.com/medic/cht-user-management/pull/197).

**Comment by freddieptf** [comment]
@henokgetachew any update on this?

**Comment by Hareet** [comment]
@freddieptf This will be ready this week. I found a few mistakes in my work from last week that I need to finish refactoring before this PR is ready:
 - modify base-single-app for optional healthcheck instead of trying to fake one
 - Adding local-path for redis

Where can I test this new helm chart and deployment? I don't see any deploys in the dev-eks cluster. Can you message me configuration settings and environment variables for me to test the new containers?

**Comment by mrjones-plip** [comment]
@Hareet - I would recommend spinning up a public dev instance of CHT Core (`hareet.dev.mm.org` - oh or `user-man-test.dev.mm.org` !), use `cht-conf` to push the correct config and then spin up a user man instance in dev context using [the deploy steps](https://github.com/medic/cht-user-management/blob/main/scripts/deploy/medic-deploy.md) which match the config you just pushed. Choose one of the [4 known configurations](https://github.com/medic/cht-user-management/blob/main/scripts/deploy/medic-deploy.md#known-cofigurations) to match CHT Core <> CHT User Man Tool (eg `users-chis-tg` <> [togo config](https://github.com/medic/config-moh-togo/))

I've set up local dev instances with docker - so I'd be happy to pair with you tomorrow if @freddieptf is busy!

**Comment by Hareet** [comment]
@mrjones-plip Thanks! matching config is a key step for me here.

> I've set up local dev instances with docker - so I'd be happy to pair with you tomorrow

Unfortunately, since we are testing the production deployment process (helm charts), we can't use local-dev compose. We would want to do local k3s and then test the helm chart. I'll see whether that's easier or do it in EKS. A k3s-helper like docker-helper would be the savior here, and be parallel to how this service would run for most of the partners using it when they self-host it :)

**Comment by paulpascal** [comment]
HI @Hareet,

Thanks for looking into, this I am messaging you  configuration settings and environment variables  to test the new containers.
I would also be glad to pair with you, or @mrjones-plip if needed, just let me know.

Thanks

cc: @mrjones-plip @freddieptf @ernestoteo

**Comment by mrjones-plip** [comment]
>>     I've set up local dev instances with docker - so I'd be happy to pair with you tomorrow
>
> Unfortunately, since we are testing the production deployment process (helm charts), we can't use local-dev compose. We would want to do local k3s and then test the helm chart. I'll see whether that's easier or do it in EKS.

Oh - sorry! I should have said, "I've helped architect the local docker development environment as well as deployed to prod with helm quite a bit - I think I could be a big help since you don't have any first hand experience deploying this".

I suspect it's easiest to use EKS per my suggestion above vs k3s.

lemme know if you wanna hand!

**Comment by Hareet** [comment]
@paulpascal @freddieptf I have a WIP PR request up to add these services to the helm chart.
While I am wrapping that up, we can use my WIP branch to deploy these updates to live projects. Please validate the testing scenario below first.

One question before that though:
- During my testing, when I navigate to the user-man tool (hareet-test-users.dev.medicmobile.org) and select the development instance, I am unable to login. 

Logs from user-man container relating to auth request:
```
[04:18:16.317] INFO (18): incoming request
    reqId: "req-69"
    req: {
      "method": "POST",
      "url": "/authenticate",
      "hostname": "hareet-test-users.dev.medicmobile.org",
      "remoteAddress": "10.71.2.198",
      "remotePort": 1406
    }
[04:18:16.381] INFO (18): request completed
    reqId: "req-69"
    res: {
      "statusCode": 200
    }
    responseTime: 64.18450164794922
```

![Image](https://github.com/user-attachments/assets/4d343bda-3786-4a3f-9a3b-579f20ca3ebe)

**Comment by paulpascal** [comment]
Thanks @freddieptf !

@Hareet , I was also able to test and login to MoH Togo Dev, it works fine, and I was even able to move a CHW post from one village to another one successfully.

![Image](https://github.com/user-attachments/assets/0f8a7eca-898d-4e99-9c3b-52ad3edcfe98)
